/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router and will be regenerated from src/routes.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GadosRouteImport } from './routes/gados'
import { Route as CamposRouteImport } from './routes/campos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as GadosSlugRouteImport } from './routes/gados.$slug'
import { Route as CamposSlugRouteImport } from './routes/campos.$slug'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const GadosRoute = GadosRouteImport.update({ id: '/gados', path: '/gados', getParentRoute: () => rootRouteImport } as any)
const CamposRoute = CamposRouteImport.update({ id: '/campos', path: '/campos', getParentRoute: () => rootRouteImport } as any)
const SobreRoute = SobreRouteImport.update({ id: '/sobre', path: '/sobre', getParentRoute: () => rootRouteImport } as any)
const ContatoRoute = ContatoRouteImport.update({ id: '/contato', path: '/contato', getParentRoute: () => rootRouteImport } as any)
const GadosSlugRoute = GadosSlugRouteImport.update({ id: '/gados/$slug', path: '/gados/$slug', getParentRoute: () => rootRouteImport } as any)
const CamposSlugRoute = CamposSlugRouteImport.update({ id: '/campos/$slug', path: '/campos/$slug', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gados': typeof GadosRoute
  '/campos': typeof CamposRoute
  '/sobre': typeof SobreRoute
  '/contato': typeof ContatoRoute
  '/gados/$slug': typeof GadosSlugRoute
  '/campos/$slug': typeof CamposSlugRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gados': typeof GadosRoute
  '/campos': typeof CamposRoute
  '/sobre': typeof SobreRoute
  '/contato': typeof ContatoRoute
  '/gados/$slug': typeof GadosSlugRoute
  '/campos/$slug': typeof CamposSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gados' | '/campos' | '/sobre' | '/contato' | '/gados/$slug' | '/campos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gados' | '/campos' | '/sobre' | '/contato' | '/gados/$slug' | '/campos/$slug'
  id: '__root__' | '/' | '/gados' | '/campos' | '/sobre' | '/contato' | '/gados/$slug' | '/campos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GadosRoute: typeof GadosRoute
  CamposRoute: typeof CamposRoute
  SobreRoute: typeof SobreRoute
  ContatoRoute: typeof ContatoRoute
  GadosSlugRoute: typeof GadosSlugRoute
  CamposSlugRoute: typeof CamposSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/gados': { id: '/gados'; path: '/gados'; fullPath: '/gados'; preLoaderRoute: typeof GadosRouteImport; parentRoute: typeof rootRouteImport }
    '/campos': { id: '/campos'; path: '/campos'; fullPath: '/campos'; preLoaderRoute: typeof CamposRouteImport; parentRoute: typeof rootRouteImport }
    '/sobre': { id: '/sobre'; path: '/sobre'; fullPath: '/sobre'; preLoaderRoute: typeof SobreRouteImport; parentRoute: typeof rootRouteImport }
    '/contato': { id: '/contato'; path: '/contato'; fullPath: '/contato'; preLoaderRoute: typeof ContatoRouteImport; parentRoute: typeof rootRouteImport }
    '/gados/$slug': { id: '/gados/$slug'; path: '/gados/$slug'; fullPath: '/gados/$slug'; preLoaderRoute: typeof GadosSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/campos/$slug': { id: '/campos/$slug'; path: '/campos/$slug'; fullPath: '/campos/$slug'; preLoaderRoute: typeof CamposSlugRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = { IndexRoute, GadosRoute, CamposRoute, SobreRoute, ContatoRoute, GadosSlugRoute, CamposSlugRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
